# Supabase Configuration

[auth]

[functions.send-welcome-email]
# Disable JWT verification for internal database trigger calls
verify_jwt = false

[functions.send-upgrade-thanks-email]
# Disable JWT verification for internal database trigger calls
verify_jwt = false

[functions.send-premium-upsell-email]
# Disable JWT verification for internal database trigger calls
verify_jwt = false

[functions.send-expiration-reminder-email]
# Disable JWT verification for internal edge function calls (called by nightly-plan-check)
verify_jwt = false

[functions.nightly-plan-check]
# Disable JWT verification for internal scheduled calls
verify_jwt = false 