// Defines the types related to actions logged in the system (local and Supabase)

/** General type of action being performed */
export type ActionType =
  | 'mark_as_read'
  | 'modify_label'
  | 'create_filter'
  | 'delete'
  | 'unsubscribe'
  | 'delete_with_exceptions'
  | 'analysis'
  | 'view'
  | 'preview'
  | 'premium_attempt'
  | 'other'
  | 'unsubscribe';

/** Specific mode for analysis actions */
export type AnalysisType = 'full' | 'quick'; // Kept for analysis-specific filters

/** Status of an action */
export type ActionStatus =
  | 'started'
  | 'preparing' // Added
  | 'analyzing' // Specific to analysis?
  | 'deleting' // Added
  | 'marking'
  | 'modifying'
  | 'unsubscribing'
  | 'creating'
  | 'completed'
  | 'error'
  | 'cancelled';

/** How an action concluded */
export type ActionEndType =
  | 'success'
  | 'partial_success'
  | 'user_stopped'
  | 'runtime_error'
  | 'token_expired' // Maybe needed?
  | 'permission_error'; // Maybe needed?

/** Structure for logging actions to Supabase */
export interface SupabaseActionLog {
  id?: string; // Optional: Assigned by Supabase
  user_id: string;
  type: ActionType;
  status: ActionStatus;
  filters?: Record<string, any>; // Flexible filters (like sender list, query used, etc.)
  estimated_emails?: number;
  count?: number; // Actual count of items processed (e.g., emails deleted, senders analyzed)
  created_at?: string; // ISO timestamp
  completed_at?: string | null; // ISO timestamp
  end_type?: ActionEndType | null;
  notes?: string | null; // e.g., error messages
}

/** Parameters needed to create a new action log */
export type CreateActionLogParams = Omit<
  SupabaseActionLog,
  'id' | 'created_at' | 'completed_at' | 'end_type'
>;

/** Structure for the action log stored locally (e.g., localStorage) */
// Re-using most of the analysis structure for now, with generic type field
export interface LocalActionLog {
  client_action_id: string; // Unique ID generated by the client
  analysis_id: string | null; // Corresponding Supabase ID (once created)
  type: ActionType; // Type of action ('analysis', 'delete', etc.)
  status: ActionStatus;
  filters?: Record<string, any>; // Matches Supabase structure for flexibility
  created_at: string; // ISO timestamp
  start_time: string; // ISO timestamp (when processing actually began)
  last_update_time: string; // ISO timestamp
  estimated_runtime_ms: number;
  current_batch_index?: number; // Optional: Track batches if applicable
  total_estimated_batches?: number; // Optional
  total_estimated_emails: number;
  processed_email_count: number; // Running count of processed items
  completed_at: string | null; // ISO timestamp
  end_type: ActionEndType | null;
  completion_reason: string | null; // e.g., error message or 'cancelled'
}

export type OperationType =
  | 'mark'
  | 'modify_label'
  | 'delete'
  | 'analysis';

export type OperationMode =
  | 'single'
  | 'full'
  | 'quick'
  | 'bulk'
  | 'read'
  | 'unread'
  | 'add'
  | 'remove'; 