// Types for action logging in both Supabase and localStorage

export type ActionType = 'analysis' | 'delete' | 'unsubscribe' | 'block';
export type ActionStatus = 'started' | 'analyzing' | 'completed' | 'error';
export type ActionEndType = 'success' | 'tab_closed' | 'user_stopped' | 'auth_failure' | 'runtime_error' | 'unknown';
export type AnalysisType = 'quick' | 'full';

// Base shared fields between Supabase and localStorage
interface BaseActionLog {
  type: ActionType;
  status: ActionStatus;
  filters: {
    type: AnalysisType;
    query: string;
  };
  created_at: string; // ISO timestamp
  completed_at: string | null;
  end_type: ActionEndType | null;
}

// Supabase action log type
export interface SupabaseActionLog extends BaseActionLog {
  id?: string; // Auto-generated by Supabase
  user_id: string;
  count?: number;
  notes?: string | null;
}

// localStorage action log type for analysis
export interface LocalActionLog extends BaseActionLog {
  client_action_id: string;  // Moved here from BaseActionLog
  analysis_id: string | null; // Supabase ID once received
  start_time: string; // ISO timestamp
  estimated_runtime_ms: number;
  current_batch_index: number;
  total_estimated_batches: number;
  total_estimated_emails: number;
  processed_email_count: number;
  completion_reason: string | null;
}

// Helper type for creating new action logs
export type CreateActionLogParams = Omit<SupabaseActionLog, 'id' | 'created_at' | 'completed_at' | 'end_type'>; 