-- Create supabase_functions schema and hooks table
CREATE SCHEMA IF NOT EXISTS supabase_functions;

CREATE TABLE IF NOT EXISTS supabase_functions.hooks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hook_table_id integer NOT NULL,
    hook_name text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    request_id bigint
);

-- Grant necessary permissions
GRANT USAGE ON SCHEMA supabase_functions TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE supabase_functions.hooks TO postgres, anon, authenticated, service_role;
